config/routes.rb
MusicAlbumCollection::Application.routes.draw do
  devise_for :users
  

  resources :albums

  root :to => 'home#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :title, :artist, :description, :cover, :user_id

  # Validations
  validates_presence_of :title, :artist, :user_id
  validates_uniqueness_of :title


  # Relationships
  belongs_to :user
  has_attached_file :cover, :styles => { :large => "640x640>", :medium => "300x300>", :thumb => "100x100>" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  # Relationships
  has_many :albums, :dependent => :destroy
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
  	@albums = current_user.albums
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
  	@album = Album.new
  end

  def edit
    @album = Album.find(params[:id])
  end

  def create
  	@album = Album.new(params[:album])
    @album.user_id = current_user.id
    
    if @album.save
      flash[:success] = "Album has been created"
      redirect_to :action => :index
    else
      render :action => :new
    end
  end

  def update
    @album = Album.find(params[:id])

    if @album.update_attributes(params[:album])
      flash[:success] = "Album was successfully updated"
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end
  
  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    
    flash[:success] = "Album was successfully deleted"
    redirect_to :action => :index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
  	  redirect_to albums_path
  	end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/_form.html.erb
<%= semantic_form_for @album, :html => { :multipart => true, :class => "form-horizontal" } do |f| %>
  <% if !@album.cover_file_name.nil? %>
  	<%= image_tag @album.cover.url(:thumb) %>
  <% end %>
  <%= f.input :cover %>
  <%= f.inputs :title, :artist, :description %>
  <%= f.submit "Save Album", :class => "btn" %>
<% end %>

app/views/albums/edit.html.erb
<h2>Edit Album</h2>

<%= render 'form' %>

app/views/albums/index.html.erb
<div class="container">
  <div class="btn-toolbar">
    <div class="btn-group pull-right">
        <a href="<%= new_album_path %>" class="btn">
          <i class="icon-plus"></i> Create New Album
        </a>
    </div>
  </div>
</div>
<br/>
<div class="container">
  <table class="table datatable">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Artist</th>
        <th>Cover</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% if @albums.empty? %>
        <tr>
          <td colspan="5"><p>Sorry, there are no albums yet.</p></td>
        </tr>
      <% else %>
        <% @albums.each do |album| %>
          <tr>
            <td><%= album.id %></td>
            <td><%= album.title %></td>
            <td><%= album.artist %></td>
            <td><%= image_tag album.cover.url(:thumb) %></td>
            <td>
              <%= link_to "Show", album_path(album) %>
              <%= link_to "Edit", edit_album_path(album) %>
              <%= link_to "Delete", album_path(album) , :confirm => 'Are you sure?', :method => :delete %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/albums/new.html.erb
<h2>Create Album</h2>

<%= render 'form' %>

app/views/albums/show.html.erb
<div class="row">
 <div class="span5">
 	<%= image_tag @album.cover.url(:large) %>
 </div>
 <div class="span7">
 	<h2><%= @album.title %></h2>
 	<h4><%= @album.artist %></h4>
 	<p><%= @album.description %></p>
 </div>
</div>

app/views/home/index.html.erb
Welcome!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MusicAlbumCollection" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">MusicAlbumCollection</a>
          <div class="container nav-collapse">
            <ul class="nav pull-right">
              <% if user_signed_in? %>
                <li><%= link_to( "Signed in as " + current_user.email, edit_user_registration_path ) %></li>
                <li><%= link_to( "Logout" , destroy_user_session_path, method: :delete ) %></li>
              <% else %>
                <li><%= link_to "Join", new_user_registration_path  %></li>
                <li><%= link_to "Login", new_user_session_path  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="container">
              <%= yield %>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <hr />
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>